# Generated by Django 5.2.4 on 2025-07-16 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(
                blank=True,
                help_text="Дата рождения пользователя.",
                null=True,
                verbose_name="Дата рождения",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Мужской"), ("F", "Женский")],
                help_text="Пол пользователя.",
                max_length=1,
                null=True,
                verbose_name="Пол",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Контактный телефон пользователя.",
                max_length=12,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефона должен начинаться с +7 или 8 и содержать 10 цифр.",
                        regex="^(?:\\+7|8)\\d{10}$",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
    ]
