[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311', 'py312'] # Укажите используемые версии Python
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv # <-- Добавьте явно, если не работает автоматически
  | _build
  | build
  | dist
  | env
  | venv # <-- Добавьте явно, если не работает автоматически
)/
'''