# Generated by Django 5.2.4 on 2025-07-16 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schedule", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_date",
                    models.DateField(
                        help_text="Конкретная дата, на которую производится запись.",
                        verbose_name="Дата записи",
                    ),
                ),
                (
                    "booking_time",
                    models.TimeField(
                        help_text="Конкретное время, на которое производится запись. Должно совпадать со временем расписания.",
                        verbose_name="Время записи",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждено"),
                            ("cancelled", "Отменено"),
                            ("completed", "Завершено"),
                        ],
                        default="pending",
                        help_text="Текущий статус записи (ожидает, подтверждено, отменено и т.д.).",
                        max_length=15,
                        verbose_name="Статус записи",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления записи"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Клиент, который осуществляет запись.",
                        limit_choices_to={"role": "client"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        help_text="Слот расписания, на который производится запись.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="schedule.schedule",
                        verbose_name="Расписание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись на тренировку",
                "verbose_name_plural": "Записи на тренировки",
                "ordering": ["-booking_date", "-booking_time"],
                "indexes": [
                    models.Index(
                        fields=["client", "booking_date"],
                        name="bookings_bo_client__a1774a_idx",
                    ),
                    models.Index(
                        fields=["schedule", "booking_date", "booking_time"],
                        name="bookings_bo_schedul_aaef1a_idx",
                    ),
                    models.Index(
                        fields=["status"], name="bookings_bo_status_233e96_idx"
                    ),
                ],
                "unique_together": {
                    ("client", "schedule", "booking_date", "booking_time")
                },
            },
        ),
    ]
